#!/usr/bin/env bash

# use xspf playlists with mpv, which does not natively support them
# depends: mpv, rofi
# license: MIT
# author: rockhazard
# (c)2021 rockhazard

usage(){
    echo "xmpv is a wrapper for mpv that parses xspf playlists for use with mpv"
    echo "SYNOPSIS: xmpv [-p | -s | -d PLAYLIST.XSPF] [MPV OPTIONS]"
    echo "-p, --xspf-playlist ... use mpv to play PLAYLIST.XSPF"
    echo "-s, --select .......... play a selected track from PLAYLIST.XSPF"
    echo "-d, --dump ............ print extracted tracks from PLAYLIST.XSPF"
    echo "-h, --help ............ print this help document"
}

list=$(mktemp -p /tmp -t xspf-tracks-tmp.XXXXXX.m3u) || exit 1
declare -A tracklist=()
warn="ERROR: Please provide a valid xspf playlist."

if [[ -a "$2" ]]; then
    playlist="$2"
    xspf_test=$(file --mime "$playlist" | grep "text/xml" | wc -l)
fi

test_playlist(){
    if [[ "$xspf_test" -lt 1 ]]; then
        echo "$warn"
        exit 1
    fi
}

convert_playlist(){
    # builds file paths list for mpv and rofi
    test_playlist
    grep "<location>.*</location" "$playlist" > "$list"
    # ASCII URL encodings prevent mpv playback, so replacing some with literals
    sed -i -e "s#<location>file://##g" -e "s#</location>##g" \
    -e "s#%26#\&#g" \
    -e "s#%28#\(#g" \
    -e "s#%29#\)#g" \
    -e "s#%5B#\[#g" \
    -e "s#%5D#\]#g" \
    -e "s#%2C#\,#g" \
    -e "s#%21#\!#g" \
    -e "s#%23#\##g" \
    -e "s#\%20# #g" \
    -e "s#\%C2\%AE#®#g" \
    -e "s#\%27#\'#g" \
    "$list"
    while IFS= read -r line; do
        tracklist["${line##*/}"]="$line"
    done < $list
}

select_track(){
    convert_playlist && choice=$(printf '%s\n' "${!tracklist[@]}"  | sort | \
    rofi -width 60 -dmenu -p "Search playlist")
    if [ "$choice" ]; then
        title=$(printf '%s\n' "${tracklist["$choice"]}")
        # allow full use of standard mpv options
        echo "${title}" | xargs -I % mpv "%" "${@:2}" # strip spaces
    else
        echo "exiting program..."
    fi
}

case "$1" in
    -d | --dump ) convert_playlist && xargs --arg-file="$list" -I % echo -e "%"
    ;;
    -h | --help ) usage
    ;;
    -s | --select ) select_track
    ;;
    -p | --xspf-playlist ) convert_playlist && mpv "$list" "${@:3}"
    ;;
    * ) mpv "$@"
    ;;
esac

trap 'rm -f "$list"' EXIT
